server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          # uri: https://github.com/krish/spring-cloud-config
          uri: https://gitlab.com/easyfit-group/easyfit
          search-paths:
           - '*service'



