server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          some-congig: qwerty123
          uri: https://gitlab.com/easyfit-group/easyfit
          search-paths:
           - '*service'



